select * from TAREAS

INSERT INTO PROYECTOS (DESCRIPCION, FE_INICIO, FE_FIN, TIEMPO, CERRADO) VALUES ("PROYECTO 1", '2009-12-5', NULL, 0, 0)

INSERT INTO TAREAS (DESCRIPCION, PORCENTAGE, FE_INICIO, FE_FIN, TIEMPO, PROYECTO, COMENTARIO) VALUES ("TAREA P1 2", 12,'2009-12-5', NULL, 0, "PROYECTO 2", "SIN COMENTARIOS")


DELETE FROM PROYECTOS WHERE DESCRIPCION = "PROYECTO 1"; DELETE FROM TAREAS WHERE PROYECTO = "PROYECTO 1"